version: '3'

services:
  apphub:
    container_name: apphub
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - '8888:80'
    # volumes:
    #   - ./apphub-data:/usr/share/nginx/html/data
